apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: simplest
spec:
  storage:
    traces:
      backend: s3
      s3:
        secret: minio
  multitenancy:
    enabled: true
    mode: openshift
    authentication:
    - tenantName: tenant-1
      tenantId: "tenant-1"
  jaegerui:
    enabled: true
    route:
      enabled: true
  observability:
    metrics:
      serviceMonitors:
        enabled: true
