apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: tempo-perf-test
spec:
  mode: deployment
  serviceAccount: otel-collector-sa
  config:
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token
    
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    exporters:
      otlp:
        endpoint: tempo-simplest-gateway.tempo-perf-test.svc.cluster.local:4317
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: tenant-1  # tenantName
      otlphttp:
        endpoint: https://tempo-simplest-gateway.tempo-perf-test.svc.cluster.local:8080/api/traces/v1/tenant-1
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: tenant-1  # tenantName
    
    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
