apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: tempo-perf-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: otel-collector-role
  namespace: tempo-perf-test
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-collector-rolebinding
  namespace: tempo-perf-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otel-collector-role
subjects:
  - kind: ServiceAccount
    name: otel-collector-sa
    namespace: tempo-perf-test
---
# Grant the otel-collector-sa Service Account permission to write traces to the 'tenant-1' tenant
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-write-traces-tenant-1
rules:
- apiGroups: [tempo.grafana.com]
  resources: [tenant-1]  # tenantName
  resourceNames: [traces]
  verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-write-traces-tenant-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-write-traces-tenant-1
subjects:
- kind: ServiceAccount
  name: otel-collector-sa
  namespace: tempo-perf-test

